version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.0
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb,sqs,s3,lambda
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-init:/docker-entrypoint-initaws.d
