models:
  - name: "gpt-4o"
    provider: 
      type: openai
      api_key_env: "OPENAI_API_KEY"
    
  - name: "gpt-4o-mini"
    provider:
      type: openai
      api_key_env: "OPENAI_API_KEY"
    
  - name: "claude-3-opus"
    provider:
      type: anthropic
      api_key_env: "ANTHROPIC_API_KEY"
    
  - name: "claude-3-sonnet"
    provider:
      type: anthropic  
      api_key_env: "ANTHROPIC_API_KEY"

functions:
  - name: "execute_plan"
    type: "chat"
    models:
      - "claude-3-opus"
      - "gpt-4o"
    timeout_ms: 30000
    
  - name: "code_generation"
    type: "json"
    models:
      - "gpt-4o"
    timeout_ms: 20000

gateway:
  bind_address: "0.0.0.0:8080"
  
observability:
  clickhouse:
    url: "http://clickhouse:8123"
    database: "tensorzero"
    username: "default"
    password: "password"