models:
  - name: "openrouter::anthropic/claude-3.5-sonnet"
    provider: openrouter
    api_key: "${OPENROUTER_API_KEY}"
  
  - name: "openai::gpt-4o"
    provider: openai
    api_key: "${OPENAI_API_KEY}"
    
  - name: "anthropic::claude-3-opus"
    provider: anthropic
    api_key: "${ANTHROPIC_API_KEY}"

functions:
  - name: "execute_plan"
    type: "chat"
    models:
      - "openrouter::anthropic/claude-3.5-sonnet"
      - "openai::gpt-4o"
    
  - name: "code_generation"
    type: "json"
    models:
      - "openai::gpt-4o"

gateway:
  port: 8080
  cors:
    allowed_origins: ["*"]
  
observability:
  clickhouse_url: "${CLICKHOUSE_URL}"
  
optimization:
  enable_dicl: true  # Dynamic in-context learning
  enable_fine_tuning: true