AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECOSYSTEMCL.AI Production Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: production
  DatabasePassword:
    Type: String
    NoEcho: true

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.1.0/24

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: 10.0.2.0/24

  # RDS Database
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for ECOSYSTEMCL.AI database
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${Environment}-forge-db
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: forge
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: 20
      DBSubnetGroupName: !Ref DBSubnetGroup

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Environment}-forge-cluster
      CapacityProviders:
        - FARGATE

  # S3 Bucket
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-forge-artifacts-${AWS::AccountId}

Outputs:
  DatabaseEndpoint:
    Value: !GetAtt Database.Endpoint.Address
  ECSClusterName:
    Value: !Ref ECSCluster
  ArtifactsBucketName:
    Value: !Ref ArtifactsBucket
