name: Optimized CI Pipeline

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/**'
      - '!packages/**/README.md'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            [
              {"name": "web",    "paths": ["packages/web/**"]},
              {"name": "worker", "paths": ["packages/worker/**"]},
              {"name": "infra",  "paths": ["packages/infra/**"]},
              {"name": "cli",    "paths": ["packages/cli/**"]}
            ]

  test:
    needs: changes
    if: ${{ needs.changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.changes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.15.1

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run coverage tests
        env:
          CI: true
        run: pnpm -F ${{ matrix.package }} test:coverage
